Transform: [Template]
Description: Example Macro Template.

Parameters:
  GitHubUser:
    Type: String
    Default: ggiallo28
  RepositoryName:
    Type: String
    Default: aws-cloudformation-macros
  BranchName:
    Type: String
    Default: master
  BucketName:
    Type: String
    Default: example-bucket
  TemplateKey:
    Type: String
    Default: Template/sns-topics-template.yaml
  Environment:
    Type: String
    Default: prod

Conditions: 
  CreateResources: !Equals [ !Ref Environment, prod ]

Resources:

  HighPriorityAlarm:
    Type: "AWS::SNS::Topic"
    Properties: 
      TopicName: !Sub High-Priority-Alarm-${Environment}

  SNSTopiInlineCondition:
    Type: Template::Git
    Condition: CreateResources
    Properties:
      Mode: Inline
      Provider: Github
      Repo: !Ref RepositoryName
      Branch: !Ref BranchName
      Path: !Ref TemplateKey
      Owner: !Ref GitHubUser
      Parameters:
        Name: 'sns-topic-template-codecommit-inline-stack-condition'
        Environment: !Ref Environment

  #SNSTopicS3:
  #  Type: Template::S3
  #  Properties:
  #    Mode: Inline
  #    Provider: S3
  #    Bucket: !Ref BucketName
  #    Key: !Ref TemplateKey
  #    Parameters:
  #      Name: 'sns-topic-template-s3-inline-stack'
  #      Environment: !Ref Environment

  SNSTopicNested:
    Type: Template::Git
    Properties:
      Mode: Nested
      Provider: Github
      Repo: !Ref RepositoryName
      Branch: !Ref BranchName
      Path: !Ref TemplateKey
      Owner: !Ref GitHubUser
      Parameters:
        Name: 'sns-topic-template-github-nested-stack'
        Environment: !Ref Environment
      NotificationARNs:
        - !Ref HighPriorityAlarm
      Tags: 
        - Key: Environment
          Value: !Ref Environment
      TimeoutInMinutes: 1
      TemplateBucket: !Ref BucketName
      TemplateKey: !Ref TemplateKey