Transform: [Template]
Description: Example Macro Template.

Parameters:
  ProjectName:
    Type: String
    Default: xp-coast/xpeppers/xpeppers-cloudformation-sample
  BranchName:
    Type: String
    Default: master
  TemplateBeanstalk:
    Type: String
    Default: alb-autoscaling-blue-green/webserver.yaml
  OAuthToken:
    Type: String
    Default: f-R8ccD4V8zu_CYGz18Y
  Environment:
    Type: String
    Default: prod
  VPCStackName:
    Type: String
    Default: VirtualPrivateCloud-TemplateVPC     

Resources:

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties: 
      Name: macro.sample
      VPCs: 
        - 
          VPCId: 
            Fn::ImportValue:
              !Sub "${VPCStackName}-VPC-id"
          VPCRegion: !Ref 'AWS::Region'

  WebServer:
    Type: Template::Git
    Properties:
      Mode: Inline
      Provider: Gitlab
      Project: !Ref ProjectName
      Branch: !Ref BranchName
      Path: !Ref TemplateBeanstalk
      OAuthToken: !Ref OAuthToken
      Parameters:
        VPCStackName: !Ref VPCStackName
        AccountName: 'xpeppers-test'
        Environment: 'production'
        Owner: 'ggiallo'
        CostCenter: 'aws'
        Project: 'macro'
        InstanceName: 'macro'
        KeyName: 'ggiallo28_2'
        AssignPublicIP: 'false'
        HostedZoneName: macro.sample
        HostedZoneID: !Ref HostedZone
        InstanceType: 't2.micro'
        ALBcertificateARN: ''
        InstanceAMI: 'ami-0323c3dd2da7fb37d'
        EnvironmentVersion: '1'
