Transform: [Template]
Description: Example Macro Template.

Parameters:
  ProjectName:
    Type: String
    Default: xp-coast/xpeppers/xpeppers-cloudformation-sample
  BranchName:
    Type: String
    Default: master
  TemplateBeanstalk:
    Type: String
    Default: dns-autoscaling/dns.yml
  OAuthToken:
    Type: String
    Default: f-R8ccD4V8zu_CYGz18Y
  Environment:
    Type: String
    Default: prod
  VPCStackName:
    Type: String
    Default: VirtualPrivateCloud-TemplateVPC     

Resources:

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties: 
      Name: macro.sample
      VPCs: 
        - 
          VPCId: 
            Fn::ImportValue:
              !Sub "${VPCStackName}-VPC-id"
          VPCRegion: !Ref 'AWS::Region'

  WebServer:
    Type: Template::Git
    Properties:
      Mode: Inline
      Provider: Gitlab
      Project: !Ref ProjectName
      Branch: !Ref BranchName
      Path: !Ref TemplateBeanstalk
      OAuthToken: !Ref OAuthToken
      Parameters:
        Customer: 'giallo'
        Project: 'macro'
        Environment: 'production'
        Owner: 'ggiallo'
        AMIid: 'ami-0323c3dd2da7fb37d'
        EC2InstanceType: 't2.micro'
        KeyName: 'ggiallo28_2'
        VPCStackName: !Ref VPCStackName
        vpcNet: '192.168.0.1'
        vpcDns: '8.8.8.8'
        onpremDomain: 'me.example.com'
        onpremDns: '192.168.0.2'
        ipSubnetA: 
          Fn::ImportValue:
            !Sub "${VPCStackName}-PublicSubnetCidrA"
        ipSubnetB: 
          Fn::ImportValue:
            !Sub "${VPCStackName}-PublicSubnetCidrB"

