Transform: [Template]
Description: Example Macro Template.

Parameters:
  ProjectName:
    Type: String
    Default: xp-coast/xpeppers/xpeppers-cloudformation-sample
  BranchName:
    Type: String
    Default: master
  TemplateVPC:
    Type: String
    Default: vpc/vpc.yml
  TemplateFlowLog:
    Type: String
    Default: flowlog-crr/flowlog.yml
  TemplateBastion:
    Type: String
    Default: single-ec2-bastion/bastion.yaml
  GitLabToken:
    Type: String
    Default: f-R8ccD4V8zu_CYGz18Y
  Environment:
    Type: String
    Default: prod
  AccountName:
    Type: String
    Default: 'xpeppers-test'
  Owner:
    Type: String
    Default: 'giallo'
  CentroCosti:
    Type: String
    Default: 'aws' 
  BastionAmiId: 
    Type: String
    Default: ami-0323c3dd2da7fb37d
  InstanceType:
    Type: String
    Default: t2.nano
  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
    Default: 'ggiallo28_2'

Resources:

  VirtualPrivateCloud:
    Type: Template::Git
    Properties:
      Mode: Inline
      Provider: Gitlab
      Project: !Ref ProjectName
      Branch: !Ref BranchName
      Path: !Ref TemplateVPC
      OAuthToken: !Ref GitLabToken
      Parameters:
        AccountName: !Ref AccountName
        Environment: !Ref Environment
        Owner: !Ref Owner
        CentroCosti: !Ref CentroCosti
        Project: !Select [ 2, !Split [ '/', !Ref ProjectName ] ]
        VpcCidr: '10.88.135.0/24'
        PrivateSubnetCidrA: '10.88.135.0/26'
        PrivateSubnetCidrB: '10.88.135.64/26'
        PublicSubnetCidrA: '10.88.135.128/26'
        PublicSubnetCidrB: '10.88.135.192/26'

  FlowLogs:
    Type: Template::Git
    DependsOn: Template::VirtualPrivateCloud
    Properties:
      Mode: Inline
      Provider: Gitlab
      Project: !Ref ProjectName
      Branch: !Ref BranchName
      Path: !Ref TemplateFlowLog
      OAuthToken: !Ref GitLabToken
      Parameters:
        Constructor: !Join ["-",[!Ref AccountName, !Ref Environment, 'flows-log']]
        VPCId: !Ref Template::VirtualPrivateCloud::VPC
        CRRDestinationBucket: !Ref Template::DefaultBucket
        CRRDestinationAccountId: !Ref AWS::AccountId

  ElasticIP:
    Type: AWS::EC2::EIP

  BastionHost:
    Type: Template::Git
    DependsOn: Template::VirtualPrivateCloud
    Properties:
      Mode: Inline
      Provider: Gitlab
      Project: !Ref ProjectName
      Branch: !Ref BranchName
      Path: !Ref TemplateBastion
      OAuthToken: !Ref GitLabToken
      Parameters:
        Environment: !Ref Environment
        Project: !Select [ 2, !Split [ '/', !Ref ProjectName ] ]
        AccountName: !Ref AccountName
        Owner: !Ref Owner
        CostCenter: !Ref CentroCosti
        ImageId: !Ref BastionAmiId
        InstanceName: 
          Fn::Join:
            - '-'
            - - !Select [ 2, !Split [ '/', !Ref ProjectName ] ]
              - !Ref Environment
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        ReservedEIP: !Ref ElasticIP
        VPCId: !Ref Template::VirtualPrivateCloud::VPC
        SubnetId: !Ref Template::VirtualPrivateCloud::PublicSubnetA




