Transform: [Template]
Description: Example Macro Template.

Parameters:
  GitHubUser:
    Type: String
    Default: ggiallo28
  ProjectName:
    Type: String
    Default: xp-coast/xpeppers/xpeppers-cloudformation-sample
  BranchName:
    Type: String
    Default: master
  TemplateVPC:
    Type: String
    Default: vpc/vpc.yml
  OAuthToken:
    Type: String
    Default: YsfRzFo-Fa5HxhhCui_-
  Environment:
    Type: String
    Default: prod

Conditions: 
  CreateResources: !Equals [ !Ref Environment, prod ]

Resources:

  HighPriorityAlarm:
    Type: "AWS::SNS::Topic"
    Properties: 
      TopicName: !Sub High-Priority-Alarm-${Environment}

  VirtualPrivateCloud:
    Type: Template::Git
    Properties:
      Mode: Inline
      Provider: Gitlab
      Project: !Ref ProjectName
      Branch: !Ref BranchName
      Path: !Ref TemplateVPC
      OAuthToken: !Ref OAuthToken
      Parameters:
        AccountName: 'test'
        Environment: !Ref Environment
        Owner: 'giallo'
        CentroCosti: 'aws'
        Project: 'no'
        VpcCidr: '10.88.135.0/24'
        PrivateSubnetCidrA: '10.88.135.0/26'
        PrivateSubnetCidrB: '10.88.135.64/26'
        PublicSubnetCidrA: '10.88.135.128/26'
        PublicSubnetCidrB: '10.88.135.192/26'



